# Stubs for elasticsearch.client.remote (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import NamespacedClient, SKIP_IN_PATH, _make_path, query_params
from typing import Any, Optional

class RemoteClient(NamespacedClient):
    def info(self, params: Optional[Any] = ...): ...
