# Stubs for elasticsearch.client.tasks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import NamespacedClient, SKIP_IN_PATH, _make_path, query_params
from typing import Any, Optional

class TasksClient(NamespacedClient):
    def list(self, params: Optional[Any] = ...): ...
    def cancel(self, task_id: Optional[Any] = ..., params: Optional[Any] = ...): ...
    def get(self, task_id: Optional[Any] = ..., params: Optional[Any] = ...): ...
