# Stubs for elasticsearch.helpers.test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from unittest import TestCase

def get_test_client(nowait: bool = ..., **kwargs: Any): ...

class ElasticsearchTestCase(TestCase):
    @classmethod
    def setUpClass(cls) -> None: ...
    def tearDown(self) -> None: ...
    @property
    def es_version(self): ...
