# Stubs for elasticsearch.client.xpack.deprecation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from elasticsearch.client.utils import NamespacedClient
from typing import Any, Optional

class DeprecationClient(NamespacedClient):
    def info(self, index: Optional[Any] = ..., params: Optional[Any] = ...): ...
