# Stubs for elasticsearch.client.xpack.graph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from elasticsearch.client.utils import NamespacedClient
from typing import Any, Optional

class GraphClient(NamespacedClient):
    def explore(self, index: Optional[Any] = ..., doc_type: Optional[Any] = ..., body: Optional[Any] = ..., params: Optional[Any] = ...): ...
