# Stubs for elasticsearch.client.xpack.license (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from elasticsearch.client.utils import NamespacedClient
from typing import Any, Optional

class LicenseClient(NamespacedClient):
    def delete(self, params: Optional[Any] = ...): ...
    def get(self, params: Optional[Any] = ...): ...
    def post(self, body: Optional[Any] = ..., params: Optional[Any] = ...): ...
