# Stubs for elasticsearch.client.xpack.migration (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from elasticsearch.client.utils import NamespacedClient
from typing import Any, Optional

class MigrationClient(NamespacedClient):
    def get_assistance(self, index: Optional[Any] = ..., params: Optional[Any] = ...): ...
    def upgrade(self, index: Any, params: Optional[Any] = ...): ...
