# Stubs for elasticsearch.client.xpack.monitoring (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from elasticsearch.client.utils import NamespacedClient
from typing import Any, Optional

class MonitoringClient(NamespacedClient):
    def bulk(self, body: Any, doc_type: Optional[Any] = ..., params: Optional[Any] = ...): ...
