# Stubs for elasticsearch.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from itertools import imap as map
from typing import Any

PY2: Any
string_types: Any
map = map
