# Stubs for elasticsearch.connection (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import Connection
from .http_requests import RequestsHttpConnection
from .http_urllib3 import Urllib3HttpConnection, create_ssl_context
