# Stubs for elasticsearch.connection.http_requests (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..compat import string_types, urlencode
from ..exceptions import ConnectionError, ConnectionTimeout, ImproperlyConfigured, SSLError
from .base import Connection
from typing import Any, Optional

REQUESTS_AVAILABLE: bool

class RequestsHttpConnection(Connection):
    session: Any = ...
    base_url: Any = ...
    def __init__(self, host: str = ..., port: int = ..., http_auth: Optional[Any] = ..., use_ssl: bool = ..., verify_certs: bool = ..., ca_certs: Optional[Any] = ..., client_cert: Optional[Any] = ..., client_key: Optional[Any] = ..., headers: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def perform_request(self, method: Any, url: Any, params: Optional[Any] = ..., body: Optional[Any] = ..., timeout: Optional[Any] = ..., ignore: Any = ..., headers: Optional[Any] = ...): ...
    def close(self) -> None: ...
