# Stubs for elasticsearch.connection.pooling (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import Connection
from typing import Any

class PoolingConnection(Connection):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
